"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
LIMIT = 4_000_000

def fibonacci_even_sum(limit: int) -> int:
    i, j = 1, 2
    fibonacci_list = [i, j]

    while i < limit and j < limit:
        i = i + j
        j = i + j
        fibonacci_list.append(i)
        fibonacci_list.append(j)

    return sum([i for i in fibonacci_list if i % 2 == 0])

# ---

if __name__ == "__main__":
    result = fibonacci_even_sum(LIMIT)
    print(result)